services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: market_user
      POSTGRES_PASSWORD: qwerty123
    volumes:
      - .postgres_data:/var/lib/postgresql
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
